### ISSUE TITLE
feature request: i18n support

### ISSUE THREAD

**Issue by blfpd** [the-mikedavis/tree-sitter-git-commit#13] opened 2023-10-31 16:27 UTC
This parser only works with locale `en_US` I presume.

Would it be possible to consider letting this parser be functional for the user’s language?

![git-commit-in-french](https://github.com/the-mikedavis/tree-sitter-git-commit/assets/2727048/63e60497-401f-47d2-ab76-cf0a73131084)

**Comment by the-mikedavis** [comment] 2023-10-31 16:43
See https://github.com/the-mikedavis/tree-sitter-git-commit/issues/4

**Comment by the-mikedavis** [comment] 2024-02-05 16:56
As discussed in #14 this is a duplicate of #4. If you're looking for support for other language's I believe you should use [`@gbprod`'s grammar](https://github.com/gbprod/tree-sitter-gitcommit) instead

**Closed as not planned by the-mikedavis** 2024-02-05 16:56 UTC
